module.exports = {
  LandingPage: require("./landingPage"),
  PhotoIdSelectionPage: require("./photoIdSelectionPage"),
  RelyingPartyPage: require("./relying-party.js"),
  ErrorPage: require("./error.js"),
  PassportDetailsPageValid: require("./passportDetailsPageValid"),
  PassportDetailsPageInvalidFuture: require("./passportDetailsPageInvalidFuture"),
  PassportDetailsPageInvalidPast: require("./passportDetailsPageInvalidPast"),
  EuDrivingLicenceDetailsPageValid: require("./euDrivingLicenceDetailsPageValid"),
  EuDrivingLicenceDetailsPageInvalid: require("./euDrivingLicenceDetailsPageInvalid"),
  NameEntryPage: require("./nameEntryPage"),
  DateOfBirthPage: require("./dateOfBirthPage"),
  CheckDetailsPage: require("./checkDetailsPage"),
  YoungScotNECDetailsPageValid: require("./youngScotNECDetailsPageValid"),
  YoungScotNECDetailsPageInvalid: require("./youngScotNECDetailsPageInvalid"),
  NonUKPassportDetailsPageValid: require("./nonUKPassportDetailsPageValid"),
  NonUKPassportDetailsPageInvalid: require("./nonUKPassportDetailsPageInvalid"),
  NationalIdentityCardEEADetailsPageValid: require("./nationalIdentityCardEEADetailsPageValid"),
  NationalIdentityCardEEADetailsPageInvalid: require("./nationalIdentityCardEEADetailsPageInvalid"),
  CitizenCardDetailsPageValid: require("./citizenCardDetailsPageValid"),
  CitizenCardDetailsPageInvalidFuture: require("./citizenCardDetailsPageInvalidFuture"),
  CitizenCardDetailsPageInvalidPast: require("./citizenCardDetailsPageInvalidPast"),
  PhotoDlDetailsPageValid: require("./photoDlDetailsPageValid"),
  PhotoDlDetailsPageInvalid: require("./photoDlDetailsPageInvalid"),
  BRPDetailsPageValid: require("./brpDetailsPageValid"),
  BRPDetailsPageInvalid: require("./brpDetailsPageInvalid"),
  PhotoIdExpiryPage: require("./photoIdExpiryPage")
};
