module.exports = {
  LandingPage: require("./landingPage"),
  PhotoIdSelectionPage: require("./photoIdSelectionPage"),
  RelyingPartyPage: require("./relying-party.js"),
  ErrorPage: require("./error.js"),
  PassportDetailsPageValid: require("./passportDetailsPageValid"),
  PassportDetailsPageInvalidFuture: require("./passportDetailsPageInvalidFuture"),
  PassportDetailsPageInvalidPast: require("./passportDetailsPageInvalidPast"),
  EuDrivingLicenceDetailsPage: require("./euDrivingLicenceDetailsPage"),
  NameEntryPage: require("./nameEntryPage"),
  DateOfBirthPage: require("./dateOfBirthPage"),
  CheckDetailsPage: require("./checkDetailsPage"),
  YoungScotNECDetailsPage: require("./youngScotNECDetailsPage"),
  NonUKPassportDetailsPageValid: require("./nonUKPassportDetailsPageValid"),
  NonUKPassportDetailsPageInvalid: require("./nonUKPassportDetailsPageInvalid"),
  NationalIdentityCardEEADetailsPage: require("./nationalIdentityCardEEADetailsPage"),
  CitizenCardDetailsPage: require("./citizenCardDetailsPage"),
  PhotoDlDetailsPageValid: require("./photoDlDetailsPageValid"),
  PhotoDlDetailsPageInvalid: require("./photoDlDetailsPageInvalid"),
  BRPDetailsPageValid: require("./brpDetailsPageValid"),
  BRPDetailsPageInvalid: require("./brpDetailsPageInvalid"),
  PhotoIdExpiryPage: require("./photoIdExpiryPage")
};
