module.exports = {
  LandingPage: require("./landingPage"),
  PhotoIdSelectionPage: require("./photoIdSelectionPage"),
  RelyingPartyPage: require("./relying-party.js"),
  ErrorPage: require("./error.js"),
  PassportDetailsPageValid: require("./passportDetailsPageValid"),
  PassportDetailsPageInvalidFuture: require("./passportDetailsPageInvalidFuture"),
  PassportDetailsPageInvalidPast: require("./passportDetailsPageInvalidPast"),
  EuDrivingLicenceDetailsPage: require("./euDrivingLicenceDetailsPage"),
  NameEntryPage: require("./nameEntryPage"),
  DateOfBirthPage: require("./dateOfBirthPage"),
  CheckDetailsPage: require("./checkDetailsPage"),
  NonUKPassportDetailsPage: require("./nonUKPassportDetailsPage"),
  NationalIdentityCardEEADetailsPage: require("./nationalIdentityCardEEADetailsPage"),
  CitizenCardDetailsPage: require("./citizenCardDetailsPage"),
  PhotoDlDetailsPageValid: require("./photoDlDetailsPageValid"),
  PhotoDlDetailsPageInvalid: require("./photoDlDetailsPageInvalid"),
  BRPDetailsPage: require("./brpDetailsPage"),
  PhotoIdExpiryPage: require("./photoIdExpiryPage")
};
