FROM node:22.16.0-alpine3.21 AS builder
WORKDIR /app
COPY src ./src
COPY package.json package-lock.json tsconfig.json run-tests.sh checkIpvResume.sh ./

RUN npm install
RUN npm run build

# to build the app. So delete node_modules and reinstall only production packages.
RUN [ "rm", "-rf", "node_modules" ]
RUN npm install --production

FROM node:22.16.0-alpine3.21 AS final
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

RUN ["apk", "--no-cache", "upgrade"]
RUN ["apk", "add", "--no-cache", "tini"]
RUN ["apk", "add", "--no-cache", "bash"]

USER appuser:appgroup

WORKDIR /app
# Copy in compile assets and deps from build container
COPY --chown=appuser:appgroup  --from=builder /app/node_modules ./node_modules
COPY --chown=appuser:appgroup  --from=builder /app/package.json ./
COPY --chown=appuser:appgroup  --from=builder /app/run-tests.sh ./
COPY --chown=appuser:appgroup  --from=builder /app/checkIpvResume.sh ./

CMD ["./run-tests.sh"]
