name: Pre-merge checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build
      - run: yarn test:coverage
      - name: Install Playwright browsers
        run: yarn playwright install --with-deps
      - run: yarn test:browser:ci
        env:
          IPV_STUB_URL: ${{ secrets.IPV_STUB_URL }}
          CUSTOM_FE_URL: http://localhost:5020
          DEVICE_INTELLIGENCE_ENABLED: true
      - run: pkill -f "node src/app.js" || true
      - name: Archive browser tests results
        uses: actions/upload-artifact@v7
        with:
          name: cic-code-coverage-report
          path: test/reports/cic-reports/

  translation-checks:
    name: i18n
    runs-on: ubuntu-latest
    steps:
      - name: Translation checks
        uses: govuk-one-login/github-actions/node/run-script@c8eefadf581d2087ce2af48b7060c1329cfa5251
        with:
          node-version: 22
          package-manager: yarn
          script: yarn check-translation

  sonar-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn test:coverage
      - if: ${{ success() && github.actor != 'dependabot[bot]' }}
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
